site_name: Ibrahim



repo_url: https://github.com/ibrahimaljalal/mkdocs_test

repo_name: GitHub
edit_uri: edit/main/docs/ 


nav:
  - Home: index.md
  - About: about.md
  - Test 1: ff.md
  - Test 2: h.md
  - hradin test: test.md
  - IFRame: iframe_test.md

theme:
  name: material
  locale: ar




markdown_extensions:
  - toc:
      baselevel: 2
  - attr_list
  - md_in_html


plugins:
  - search
  - macros

extra_css:
  - style.css







